// Code generated by "stringer -type=SourceType"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SourceTypeUnspecified-0]
	_ = x[SourceTypeDevice-1]
	_ = x[SourceTypeService-2]
	_ = x[SourceTypeExternalService-3]
	_ = x[SourceTypeTestService-4]
}

const _SourceType_name = "SourceTypeUnspecifiedSourceTypeDeviceSourceTypeServiceSourceTypeExternalServiceSourceTypeTestService"

var _SourceType_index = [...]uint8{0, 21, 37, 54, 79, 100}

func (i SourceType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SourceType_index)-1 {
		return "SourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SourceType_name[_SourceType_index[idx]:_SourceType_index[idx+1]]
}
