# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grid/v1/topology.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16grid/v1/topology.proto\x12\x07grid.v1\"8\n\x08Topology\x12\x1c\n\tcreatedAt\x18\x01 \x01(\x03R\tcreatedAt\x12\x0e\n\x02tp\x18\x02 \x01(\x0cR\x02tp\"\xa1\x02\n\x0fTopologicalNode\x12 \n\x0bTerminalIds\x18\x01 \x03(\tR\x0bTerminalIds\x12\x30\n\x13\x43onnectivityNodeIds\x18\x02 \x03(\tR\x13\x43onnectivityNodeIds\x12\x30\n\x13PowerTransferEndIds\x18\x03 \x03(\tR\x13PowerTransferEndIds\x12@\n\x1b\x43onnectivityNodeContainerId\x18\x04 \x01(\tR\x1b\x43onnectivityNodeContainerId\x12$\n\rBaseVoltageId\x18\x05 \x01(\tR\rBaseVoltageId\x12 \n\x0b\x42\x61seVoltage\x18\x06 \x01(\x01R\x0b\x42\x61seVoltage\"C\n\x11TopologicalIsland\x12.\n\x12TopologicalNodeIds\x18\x01 \x03(\tR\x12TopologicalNodeIds\"\xa8\x03\n\x10\x43omputedTopology\x12\x12\n\x04\x65qId\x18\x01 \x01(\tR\x04\x65qId\x12[\n\x10topologicalNodes\x18\x02 \x03(\x0b\x32/.grid.v1.ComputedTopology.TopologicalNodesEntryR\x10topologicalNodes\x12\x61\n\x12topologicalIslands\x18\x03 \x03(\x0b\x32\x31.grid.v1.ComputedTopology.TopologicalIslandsEntryR\x12topologicalIslands\x1a]\n\x15TopologicalNodesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x18.grid.v1.TopologicalNodeR\x05value:\x02\x38\x01\x1a\x61\n\x17TopologicalIslandsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32\x1a.grid.v1.TopologicalIslandR\x05value:\x02\x38\x01\x42\x0bZ\t./grid/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grid.v1.topology_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./grid/v1'
  _globals['_COMPUTEDTOPOLOGY_TOPOLOGICALNODESENTRY']._loaded_options = None
  _globals['_COMPUTEDTOPOLOGY_TOPOLOGICALNODESENTRY']._serialized_options = b'8\001'
  _globals['_COMPUTEDTOPOLOGY_TOPOLOGICALISLANDSENTRY']._loaded_options = None
  _globals['_COMPUTEDTOPOLOGY_TOPOLOGICALISLANDSENTRY']._serialized_options = b'8\001'
  _globals['_TOPOLOGY']._serialized_start=35
  _globals['_TOPOLOGY']._serialized_end=91
  _globals['_TOPOLOGICALNODE']._serialized_start=94
  _globals['_TOPOLOGICALNODE']._serialized_end=383
  _globals['_TOPOLOGICALISLAND']._serialized_start=385
  _globals['_TOPOLOGICALISLAND']._serialized_end=452
  _globals['_COMPUTEDTOPOLOGY']._serialized_start=455
  _globals['_COMPUTEDTOPOLOGY']._serialized_end=879
  _globals['_COMPUTEDTOPOLOGY_TOPOLOGICALNODESENTRY']._serialized_start=687
  _globals['_COMPUTEDTOPOLOGY_TOPOLOGICALNODESENTRY']._serialized_end=780
  _globals['_COMPUTEDTOPOLOGY_TOPOLOGICALISLANDSENTRY']._serialized_start=782
  _globals['_COMPUTEDTOPOLOGY_TOPOLOGICALISLANDSENTRY']._serialized_end=879
# @@protoc_insertion_point(module_scope)
