# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zaphiro/platform/v1/blacklist.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#zaphiro/platform/v1/blacklist.proto\x12\x13zaphiro.platform.v1\"3\n\tBlacklist\x12&\n\x0emeasurementIds\x18\x01 \x03(\tR\x0emeasurementIdsB\x0fZ\r./platform/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zaphiro.platform.v1.blacklist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r./platform/v1'
  _globals['_BLACKLIST']._serialized_start=60
  _globals['_BLACKLIST']._serialized_end=111
# @@protoc_insertion_point(module_scope)
