# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c37118/v1/conf2.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63\x33\x37\x31\x31\x38/v1/conf2.proto\x12\tc37118.v1\"\x86\x01\n\nConf2Frame\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x16.c37118.v1.Conf2HeaderR\x06header\x12+\n\x07\x63onfigs\x18\x02 \x03(\x0b\x32\x11.c37118.v1.ConfigR\x07\x63onfigs\x12\x1b\n\tDATA_RATE\x18\x03 \x01(\rR\x08\x44\x41TARATE\"\xb9\x01\n\x0b\x43onf2Header\x12\x12\n\x04SYNC\x18\x01 \x01(\rR\x04SYNC\x12\x1c\n\tFRAMESIZE\x18\x02 \x01(\rR\tFRAMESIZE\x12\x16\n\x06IDCODE\x18\x03 \x01(\rR\x06IDCODE\x12\x10\n\x03SOC\x18\x04 \x01(\rR\x03SOC\x12\x18\n\x07\x46RACSEC\x18\x05 \x01(\rR\x07\x46RACSEC\x12\x1b\n\tTIME_BASE\x18\x06 \x01(\rR\x08TIMEBASE\x12\x17\n\x07NUM_PMU\x18\x07 \x01(\rR\x06NUMPMU\"\x98\x02\n\x06\x43onfig\x12\x10\n\x03STN\x18\x01 \x01(\tR\x03STN\x12\x16\n\x06IDCODE\x18\x02 \x01(\rR\x06IDCODE\x12\x16\n\x06\x46ORMAT\x18\x03 \x01(\rR\x06\x46ORMAT\x12\x14\n\x05PHNMR\x18\x04 \x01(\rR\x05PHNMR\x12\x14\n\x05\x41NNMR\x18\x05 \x01(\rR\x05\x41NNMR\x12\x14\n\x05\x44GNMR\x18\x06 \x01(\rR\x05\x44GNMR\x12\x14\n\x05\x43HNAM\x18\x07 \x01(\tR\x05\x43HNAM\x12\x16\n\x06PHUNIT\x18\x08 \x03(\rR\x06PHUNIT\x12\x16\n\x06\x41NUNIT\x18\t \x03(\rR\x06\x41NUNIT\x12\x18\n\x07\x44IGUNIT\x18\n \x03(\rR\x07\x44IGUNIT\x12\x12\n\x04\x46NOM\x18\x0b \x01(\rR\x04\x46NOM\x12\x16\n\x06\x43\x46GCNT\x18\x0c \x01(\rR\x06\x43\x46GCNTB\rZ\x0b./c37118/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'c37118.v1.conf2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./c37118/v1'
  _globals['_CONF2FRAME']._serialized_start=37
  _globals['_CONF2FRAME']._serialized_end=171
  _globals['_CONF2HEADER']._serialized_start=174
  _globals['_CONF2HEADER']._serialized_end=359
  _globals['_CONFIG']._serialized_start=362
  _globals['_CONFIG']._serialized_end=642
# @@protoc_insertion_point(module_scope)
