# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/v1/task.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16platform/v1/task.proto\x12\x0bplatform.v1\x1a\x19google/protobuf/any.proto\"K\n\tParameter\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyR\x05value\"\x8f\x01\n\x04Task\x12\x31\n\x08taskType\x18\x01 \x01(\x0e\x32\x15.platform.v1.TaskTypeR\x08taskType\x12\x1c\n\tcreatedAt\x18\x02 \x01(\x03R\tcreatedAt\x12\x36\n\nparameters\x18\x03 \x03(\x0b\x32\x16.platform.v1.ParameterR\nparameters\"\xc9\x01\n\x0cNotification\x12I\n\x10notificationType\x18\x01 \x01(\x0e\x32\x1d.platform.v1.NotificationTypeR\x10notificationType\x12\x1c\n\tcreatedAt\x18\x02 \x01(\x03R\tcreatedAt\x12\x18\n\x07message\x18\x03 \x01(\tR\x07message\x12\x36\n\nparameters\x18\x04 \x03(\x0b\x32\x16.platform.v1.ParameterR\nparameters*\x81\x01\n\x08TaskType\x12\x19\n\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14TASK_TYPE_COLLECTION\x10\x01\x12\x16\n\x12TASK_TYPE_TOPOLOGY\x10\x02\x12\x13\n\x0fTASK_TYPE_STATE\x10\x03\x12\x13\n\x0fTASK_TYPE_FAULT\x10\x04*\xf7\x01\n\x10NotificationType\x12!\n\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12#\n\x1fNOTIFICATION_TYPE_DATA_COMPLETE\x10\x01\x12(\n$NOTIFICATION_TYPE_DATA_TIMEOUT_SHORT\x10\x02\x12)\n%NOTIFICATION_TYPE_DATA_TIMEOUT_MEDIUM\x10\x03\x12\x1d\n\x19NOTIFICATION_TYPE_TRIGGER\x10\x04\x12\'\n#NOTIFICATION_TYPE_TOPOLOGY_COMPUTED\x10\x05\x42\x0fZ\r./platform/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'platform.v1.task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r./platform/v1'
  _globals['_TASKTYPE']._serialized_start=494
  _globals['_TASKTYPE']._serialized_end=623
  _globals['_NOTIFICATIONTYPE']._serialized_start=626
  _globals['_NOTIFICATIONTYPE']._serialized_end=873
  _globals['_PARAMETER']._serialized_start=66
  _globals['_PARAMETER']._serialized_end=141
  _globals['_TASK']._serialized_start=144
  _globals['_TASK']._serialized_end=287
  _globals['_NOTIFICATION']._serialized_start=290
  _globals['_NOTIFICATION']._serialized_end=491
# @@protoc_insertion_point(module_scope)
