name: Validate PR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check-pr:
    uses: zaphiro-technologies/github-workflows/.github/workflows/check-pr.yaml@main
    secrets: inherit
