name: Markdown Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdown-checker:
    uses: zaphiro-technologies/github-workflows/.github/workflows/markdown.yaml@main
    with:
      md-lint-globs: |
        **/*.{md,MD}
        #.github
        #docs/**/*.{md,MD}
