name: Release Notes Management
on:
  push:
    tags:
      - "*"
  pull_request_review:
  pull_request:
    branches: [main]
  release:
    types:
      - published
      
jobs:
  release-notes:
    uses: zaphiro-technologies/github-workflows/.github/workflows/release-notes.yaml@main
    secrets: inherit
