name: Update Trivy Cache

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  update-trivy-db:
    uses: zaphiro-technologies/github-workflows/.github/workflows/trivy-cache-update.yaml@main
    secrets: inherit
